---
version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/wt-api
    environment:
      ENV_NAME: dev
      AWS_PROFILE: default
      AWS_DEFAULT_REGION: us-east-1
    #links:
      #- redis
      #- database
    ports:
      - "8080:8080"
    #depends_on:
      #- redis
      #- database
    volumes:
      - /home/krogebry/.aws/:/root/.aws/
  #redis:
    #image: redis
  #database:
    #image: mongo
    #ports:
      #- "27017:27017"
    #volumes:
      #- /mnt/data/wt/mongodb:/data/db

