---
version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/wt-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - database
  redis:
    image: redis
  database:
    image: mongo
