#!/usr/bin/env ruby
# https://gist.github.com/themoxman/1d137b9a1729ba8722e4
require 'aws-sdk'
s3_client = Aws::S3::Client.new(region: ENV['AWS_DEFAULT_REGION'])
kms_client = Aws::KMS::Client.new(region: ENV['AWS_DEFAULT_REGION'])

#creds = Aws::SharedCredentials.new()
#s3_client = Aws::S3::Client.new(region: ENV['AWS_DEFAULT_REGION'], credentials: creds)
#kms_client = Aws::KMS::Client.new(region: ENV['AWS_DEFAULT_REGION'], credentials: creds)

# retrieve cmk key id
aliases = kms_client.list_aliases.aliases
key = aliases.find { |alias_struct| alias_struct.alias_name == format("alias/workout-tracker-%s", ENV['ENV_NAME']) }
key_id = key.target_key_id

# encryption client
s3_encryption_client = Aws::S3::Encryption::Client.new(
  client: s3_client,
  kms_key_id: key_id,
  kms_client: kms_client,
)

response = s3_encryption_client.get_object(bucket: 'workout-tracker', key: format('%s/env', ENV['ENV_NAME']))

exports = ""
response.body.read.each_line { |line| exports << "export #{line.chomp};" }

puts exports
